#Texte zu den Commands

System:

  #Prefix

  Prefix: '&8[&4MultiWorld&8] &r'

  #AutoWorldLoadList

  Autoload:
    -

Multiworld:

  Defaultworld: world

  #Weltenanzahl

  #Spieler
  g1: 1
  v1: 0

  #Vip
  g2: 1
  v2: 1

  #Superviser
  g3: 2
  v3: 2